import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gestion Social",
  description: "Generated by create Yilbert Luna",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  relative antialiased min-h-dvh bg-cover bg-no-repeat bg-center bg-[url(../../public/indexbackground.jpg)]`}
      >
        {children}
      </body>
    </html>
  );
}
